/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koopi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author M C S
 */
public class CustomerDetailsPage extends javax.swing.JFrame {

     private static final String username = "root";
    private static final String password = "Hashini@0730";
    private static final String dataConn = "jdbc:mysql://localhost:3306/koopi";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i;
    Statement st;
    /**
     * Creates new form CustomerDetailsPage
     */
    public CustomerDetailsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //=============================================================================
    
    //Order tableobj = new Order();
    
    public void clear(){
             jtxtcoustomername.setText("");
             jtxtgroupsize.setText("");
             jlabselecttable.setText("");
    }
    
    /*public void changepage(){
        new Order().setVisible(true);
        this.setVisible(false);
    }
    */
     
    
    
    
    
    //=============================================================================
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtcoustomername = new javax.swing.JTextField();
        jtxtgroupsize = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtnmakeOrder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlabselecttable = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel4.setText(" Customer");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 50, 131, 42));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Your Group Size");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));
        getContentPane().add(jtxtcoustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 150, 30));
        getContentPane().add(jtxtgroupsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 150, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Your name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic", 3, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, 40));

        jbtnmakeOrder.setText(" Make Order");
        jbtnmakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmakeOrderActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmakeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel3.setText("To search table press button");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, 50));

        jLabel5.setText(" your table number is");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 40));
        jPanel1.add(jlabselecttable, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 480, 540));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngtree-vector-management-icon-png-image_695895.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 350, 280));

        label1.setText("label1");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           st=sqlConn.createStatement();
           
          
           byte size = Byte.parseByte(jtxtgroupsize.getText());
           
             
           
           //fix queary error
           String query_se = " SELECT tableNumber FROM tablesarrangment WHERE seats = "+size+" AND tableNumber NOT IN (SELECT tableNumber FROM customertable) LIMIT 1" ;
           
            rs = st.executeQuery(query_se); 
            if (rs.next()) {
            int tableNumber = rs.getInt("tableNumber");
            jlabselecttable.setText(Integer.toString(tableNumber));
            } else {
             //--  jtxtselecttable.setText("No tables available");
             String query_th = " SELECT tableNumber FROM tablesarrangment WHERE seats > "+size+" AND tableNumber NOT IN (SELECT tableNumber FROM customertable) LIMIT 1" ;
             rs = st.executeQuery(query_th); 
             
             if (rs.next()){
            int tableNumber = rs.getInt("tableNumber");
            jlabselecttable.setText(Integer.toString(tableNumber));
             } else{
                 jlabselecttable.setText("No tables availble");
             }
            
             
            }
             
           
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CustomerDetailsPage.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex);
        }finally {
          try {
            if (st != null) {
                st.close();
                }
            if (sqlConn != null) {
                sqlConn.close();
            }
          } catch (SQLException ex) {
            Logger.getLogger(CustomerDetailsPage.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnmakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmakeOrderActionPerformed
         try {
             // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            st=sqlConn.createStatement();
             
             String cusomername = jtxtcoustomername.getText();
             byte size = Byte.parseByte(jtxtgroupsize.getText());
             byte selecttable = Byte.parseByte( jlabselecttable.getText());
             
             String query = "insert into customertable values(' "+cusomername+" ',"+size+","+selecttable+") ";
             st.executeUpdate(query);
             
            
              
              
             clear();
             //changepage();
             
             
             
             
         } catch (SQLException | ClassNotFoundException ex) {
             Logger.getLogger(CustomerDetailsPage.class.getName()).log(Level.SEVERE, null, ex);
         }finally {
          try {
            if (st != null) {
                st.close();
                }
            if (sqlConn != null) {
                sqlConn.close();
            }
          } catch (SQLException ex) {
            Logger.getLogger(CustomerDetailsPage.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
         
         
    }//GEN-LAST:event_jbtnmakeOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetailsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnmakeOrder;
    private javax.swing.JLabel jlabselecttable;
    private javax.swing.JTextField jtxtcoustomername;
    private javax.swing.JTextField jtxtgroupsize;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
