/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koopi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M C S
 */
public class order extends javax.swing.JFrame {
    
    
    private static final String username = "root";
    private static final String password = "Hashini@0730";
    private static final String dataConn = "jdbc:mysql://localhost:3306/koopi";
    
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i;
    Statement st;

    /**
     * Creates new form order
     */
    public order() {
        initComponents();
        Updatemenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //===========================================================================================================================
    
    private void Updatemenu(){
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst =  sqlConn.prepareStatement("select * from updatemenu");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jtablemenu.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for( i = 1; i <= q; i++){
                    columnData.add(rs.getString("name"));
                    columnData.add(rs.getString("quantity")); 
                    columnData.add(rs.getString("price")); 
                }
                RecordTable.addRow(columnData);
            }
            
        }
        catch(ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }finally {
          try {
            if (st != null) {
                st.close();
                }
            if (sqlConn != null) {
                sqlConn.close();
            }
          } catch (SQLException ex) {
            Logger.getLogger(  order.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
    }
    
    //==========================================================================================================================
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtablemenu = new javax.swing.JTable();
        jlabname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabprice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtxquantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtablemenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price"
            }
        ));
        jtablemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablemenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablemenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 23, -1, 716));

        jlabname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlabname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, 40));

        jLabel2.setText("Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 40, 30));

        jlabprice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlabprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 40));

        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 163, 78, 32));
        getContentPane().add(jtxtxquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 163, 99, 32));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtablemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablemenuMouseClicked
        // TODO add your handling code here:
         DefaultTableModel RecordTable = (DefaultTableModel)jtablemenu.getModel();
        int selectedRows = jtablemenu.getSelectedRow();
        
        jlabname.setText(RecordTable.getValueAt(selectedRows, 0).toString());
        jlabprice.setText(RecordTable.getValueAt(selectedRows, 2).toString());
        jtxtxquantity.setText(RecordTable.getValueAt(selectedRows, 1).toString());
         
    }//GEN-LAST:event_jtablemenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabname;
    private javax.swing.JLabel jlabprice;
    private javax.swing.JTable jtablemenu;
    private javax.swing.JTextField jtxtxquantity;
    // End of variables declaration//GEN-END:variables
}
