/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package koopi;

import java.text.*;
import java.sql.*;
import javax.swing.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author M C S
 */
public class TableArrangment extends javax.swing.JFrame {
    
    private static final String username = "root";
    private static final String password = "Hashini@0730";
    private static final String dataConn = "jdbc:mysql://localhost:3306/koopi";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i;
    Statement st;

    /**
     * Creates new form TableArrangment
     */
    public TableArrangment() {
        initComponents();
        UpdateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //==========================function========================================
    private void UpdateDB(){
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst =  sqlConn.prepareStatement("select * from tablesarrangment");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for( i = 1; i <= q; i++){
                    columnData.add(rs.getString("tableNumber"));
                    columnData.add(rs.getString("seats"));        
                }
                RecordTable.addRow(columnData);
            }
            
        }
        catch(ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }finally {
          try {
            if (st != null) {
                st.close();
                }
            if (sqlConn != null) {
                sqlConn.close();
            }
          } catch (SQLException ex) {
            Logger.getLogger(TableArrangment.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
    }
    
    public void Clear(){
        jtxtTableNumber.setText("");
        jtxtSeats.setText("");
    }
   
    //==========================End Function====================================
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTableNumber = new javax.swing.JTextField();
        jtxtSeats = new javax.swing.JTextField();
        jbtnAdd = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setText(" Table Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 203, 150, 45));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Seats");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 150, 45));

        jtxtTableNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTableNumberActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtTableNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 200, 119, 45));
        getContentPane().add(jtxtSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 266, 119, 45));

        jbtnAdd.setText(" Add");
        jbtnAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 463, 116, 51));

        jbtnReset.setText(" Reset");
        jbtnReset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 463, 116, 51));

        jbtnUpdate.setText(" Update");
        jbtnUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 602, 116, 47));

        jbtnRemove.setText(" Remove");
        jbtnRemove.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 602, 116, 47));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table Number", "Seats"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 521, 530));

        jLabel3.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText(" Table Arrangement");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 607, 90));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel4.setText("Manager");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 50, 131, 42));

        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 710, 154, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 400, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contollers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Felix Titling", 3, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 410, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTableNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTableNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTableNumberActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
         Clear();
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           pst =  sqlConn.prepareStatement("insert into tablesarrangment (tableNumber,seats)value (?,?)"); 
           
           pst.setString(1,jtxtTableNumber.getText());
           pst.setString(2,jtxtSeats.getText());
        
           pst.executeUpdate();
           JOptionPane.showMessageDialog(this, "record added");
           UpdateDB();
           Clear();
           
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TableArrangment.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }finally {
          try {
            if (st != null) {
                st.close();
                }
            if (sqlConn != null) {
                sqlConn.close();
            }
          } catch (SQLException ex) {
            Logger.getLogger(TableArrangment.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int selectedRows = jTable1.getSelectedRow();
        
        jtxtTableNumber.setText(RecordTable.getValueAt(selectedRows, 0).toString());
        jtxtSeats.setText(RecordTable.getValueAt(selectedRows, 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           st=sqlConn.createStatement();
           
           byte no = Byte.parseByte(jtxtTableNumber.getText());
           byte seats = Byte.parseByte(jtxtSeats.getText());
           
           String query = " update tablesarrangment set seats = ' "+seats+" ' where tableNumber ="+no;
           int result = st.executeUpdate(query);

           
         
           JOptionPane.showMessageDialog(this, "record updated");
           UpdateDB();
           Clear();
           
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TableArrangment.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null, ex);
        }finally {
          try {
            if (st != null) {
                st.close();
                }
            if (sqlConn != null) {
                sqlConn.close();
            }
          } catch (SQLException ex) {
            Logger.getLogger(TableArrangment.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        // TODO add your handling code here:
         try {
           Class.forName("com.mysql.cj.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           st=sqlConn.createStatement();
           
           byte no = Byte.parseByte(jtxtTableNumber.getText());
           String query = "delete from tablesarrangment where tableNumber="+no;
           int result = st.executeUpdate(query);
           JOptionPane.showMessageDialog(this, result+"record deleted!");
           UpdateDB();
           Clear();
    } catch (SQLException | ClassNotFoundException ex) {
        Logger.getLogger(TableArrangment.class.getName()).log(Level.SEVERE, null, ex);
    }
      finally {
         try {
              if (st != null) {
                  st.close();
                }
              if (sqlConn != null) {
                  sqlConn.close();
                }
           } catch (SQLException ex) {
               Logger.getLogger(TableArrangment.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ManagerHomePage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableArrangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableArrangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableArrangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableArrangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableArrangment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtSeats;
    private javax.swing.JTextField jtxtTableNumber;
    // End of variables declaration//GEN-END:variables
}
